apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check
    app.kubernetes.io/part-of: e2e-nodejs
  name: nodejs-health-check
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check
    spec:
      containers:
      - image: quay.io/susdas_quay_org/e2e-demos-wkiv-tenant/e2e-nodejs/nodejs-health-check@sha256:805f7e27a0a21b56fa4d8d32bff8189e69841612135e6dbd8131fac2349b9f22
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
